---
title: "Kenpom Top 50 Teams 11/13/2025"
author: "Joel Winner"
date: 2025-06-04T00:00:00-05:00
categories: ["CBBHoops"]
tags: ["2025-26 Season"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cfbplotR)
```

```{r, include=FALSE}
kp <- read_csv("C:\\Users\\winne\\Downloads\\11.13.25 KenPom top 50.csv")
midx <- mean(range(kp$ORtg))
midy <- mean(range(kp$DRtg))
```

```{r,include=FALSE}
p <- ggplot(data = kp, aes(x = ORtg, y = DRtg)) +
  geom_vline(xintercept = midx) + 
  geom_hline(yintercept = midy) +
  geom_cfb_logos(aes(team = Team), width = 0.057) +
  labs(title = "Kenpom Top 50 Teams", x = "Offensive rating", y = "Defensive Rating", subtitle = "11/13/25") +
  theme_minimal()
  
```

```{r,include=FALSE}
kpPlot <- p +
  # Offense (horizontal)
  annotate("text",
           x = max(kp$ORtg) + 1,
           y = midy,
           label = "Better Offense →",
           hjust = 1, vjust = -0.5,
           size = 3, fontface = "bold") +

  # Defense (vertical)
  annotate("text",
           x = min(kp$ORtg) + 1,
           y = midy + 3,
           label = "↑ Worse Defense",
           hjust = 0.5, vjust = 1,
           size = 3, fontface = "bold")


```

```{r}
kpPlot
```

